## makeCacheMatrix creates a special "matrix", which is a list containing a function to
## 1. set the matrix 2. get the matrix 3. set the inverse 4. get the inverse
## x is a square invertible matrix

makeCacheMatrix <- function(x = matrix()) {
        cache <- NULL
        set <- function(y) {
               x <<- y
               cache <<- NULL
        }
        get <- function() x
        setInverse <- function(inverse) cache <<- inverse
        getInverse <- function() cache
        list(set = set, get = get,
             setInverse = setInverse,
             getInverse = getInverse)
}

## list generated by makeCacheMatrix serves as input for cacheSolve

## cacheSolve computes the inverse of the special "matrix" returned by makeCacheMatrix above 
## If the inverse has already been calculated 
## then cacheSolve should retrieve the inverse from the cache


cacheSolve <- function(x, ...) {
          cache <- x$getInverse()
          
          ## if inverse has been calculated
          ## get it from the cache and skip the computation
          
          if(!is.null(cache)) {
                message("getting cached data")
                return(cache)
          }
          
          ## otherwise, calculate the inverse
          
          matrix <- x$get()
          cache <- solve(matrix, ...)
          x$setInverse(cache)
          return(cache)
}
